### PR TITLE
Fix builds with GHC 8.8.1 and newer `hashable`.

### PR DESCRIPTION
**Pull request by patrickt**
`hashable` is up to 1.3 and `fail` is no longer a part of `Monad`.

### CODE REVIEW

**Comment by patrickt** [comment]
Not clear to me why the unit tests are failing: it looks like a Stack issue, which is puzzling, as I didn’t change the stack.yml in any way.

**Comment by jwaldmann** [comment]
This patch *only* works for ghc-8.8? I get
```
cabal --with-ghc=/opt/ghc/ghc-8.6.5/bin/ghc build
...
src/Control/Distributed/Process/Internal/Types.hs:356:14: error:
    Not in scope: type constructor or class ‘MonadFail’
```
I think this can be repaired with an extra
```
import Control.Monad.Fail (MonadFail)
```
Then it compiles with ghc-8.4, 8.6. 8.8.

**Comment by patrickt** [comment]
Oop! Good catch. My apologies; fixing.

**Comment by patrickt** [comment]
Still getting an error with Stack, though I’ve verified it’s good on 8.4-8.8.

**Comment by alexbiehl** [comment]
@patrickt your patch is fine. I think stack 2 snuck in somehow. https://github.com/haskell-distributed/distributed-process/pull/342 has the cure.

**Comment by AJChapman** [comment]
Is there anything currently stopping this PR from being merged? Does it just need to be rebased against master? I'd like to see it merged as this issue is breaking my build on Nix.

**Comment by joelmccracken** [comment]
closed via #361
